version: '3'

services:

  postgres:
    image: postgres:10.8-alpine
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
    expose:
      - "5432"
    labels:
      traefik.http.services.postgres.loadbalancer.server.port: 5432
    depends_on:
      - traefik

  pgadmin:
    image: dpage/pgadmin4:4.11
    expose:
      - "1111"
    environment:
      PGADMIN_LISTEN_PORT: "1111"
      PGADMIN_DEFAULT_EMAIL: "pgadmin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    labels:
      traefik.http.services.pgadmin.loadbalancer.server.port: 1111
    depends_on:
      - traefik
      - postgres

  traefik:
    image: traefik:2.2
    command:
      - --providers.docker.defaultRule=Host(`{{ normalize .Name }}.docker.localhost`)
      - --api.insecure=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
